root: true
env:
  browser: true
  es2021: true
  amd: true
  node: true
extends:
  - 'plugin:react/recommended'
  - 'eslint:recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:prettier/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
settings:
  react:
    version: 'detect'
plugins:
  - react
rules: 
  'prettier/prettier': ['error', {}, { usePrettierrc: true }] 
  'react/react-in-jsx-scope': 'off'
  'jsx-a11y/anchor-is-valid': 
    - 'error'
    - components:
        - 'Link'
      specialLink:
        - 'hrefLeft'
        - 'hrefRight'
      aspects:
        - 'invalidHref'
        - 'preferButton'
