# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or orejobs that can run sequentially or in parallel
jobs:

  quality:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: npm install -g jsdoc
    - run: yarn run lint

  build:
    runs-on: ubuntu-latest
    needs:
      - quality
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn run build
    - run: yarn run docs

  release:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - run: yarn install
    - run: yarn global add semantic-release
    - run: semantic-release